version: '3'
services:
  postgres:
    image: postgis
    ports:
      - "5433:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gis
    volumes:
      - ../data:/var/lib/postgresql/data
